version: "3.7"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    hostname: redis
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbtest
      MYSQL_DATABASE: deno-rest-dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: dbtest
    volumes:
      - ./docker/data/db:/var/lib/mysql
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9030:8000"
    environment:
      ENV: development
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql
      - redis

networks:
  deno-rest-network:
    name: deno-rest-network
