version: "3.7"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    hostname: redis
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9030:8000"
    environment:
      ENV: development
    volumes:
      - ./:/var/www/app
    depends_on:
      - redis

networks:
  deno-rest-network:
    name: deno-rest-network
